#!/usr/bin/env bash

#CAUTION the following line explicitly excludes hostnames containing underscores
hostlist=$(host -l physik-pool.tu-berlin.de|grep has\ address|grep -o '^[-0-9a-zA-Z.]*')

for longhost in $hostlist
do 
	shorthost=${longhost%%.*}
	addr=$(host $longhost|tail -n 1|sed 's/.*has address \([0-9a-fA-F.:]*\)/\1/')
	ssh-keygen -f $1 -F $shorthost|grep -v '^#'|sed "s/^[^ ]*/$shorthost/"
	ssh-keygen -f $1 -F $longhost|grep -v '^#'|sed "s/^[^ ]*/$longhost/"
	ssh-keygen -f $1 -F $addr|grep -v '^#'|sed "s/^[^ ]*/$addr/"
done

